sudo: required
language: node_js
node_js:
- 8
services:
- docker
before_install:
- npm install -g grunt
script:
- npm i
- grunt
- ls dist
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "testnet" ]]; then
  docker tag $REPO:testnet; docker push $REPO:testnet; fi
env:
  matrix:
  - secure: gnbgxpeywqYUOBBrxp9m22KTDe6igJqShhsonrAn/y0ROJbYqNkWDLC289X0cS4AQGWQl7i+ACweetdDBhTfAUS9rn0GqxZXw2Ssev+DEEUIUed3w6RTo62QVuvxDuZYJiXzdi9uZlWcrrf6Oj5t5+P3RRt5AlPXkJJ1NxHOln7GbQ5ju6ZzGMaVo/GNEhoHYE03tWg+Vz7xAGtsi4MApeSSl+jHQQI2BXMj1VekD79j35JP1FiCXgYWsTkTP3/74Fi4zoZrcaJZvJs5tDI3BV+davLmXJKwjdoDZXW9hwWoaoPAzomhvyK+hPpuf5b/6uPtnnlzVFYW+yuIOChwLhtAM7AbhAKA4lcV/5hPXBgTKvIO94KcWZiPxg+guHJj48SYdU3YUuSXJk2703j4POolQAY5JUaygVuv07SUbbfvpI6/EOwnicX2i4Qe13oRZUZz/fBER2BMpoEsSDo6HscOHZc+hBBNU+kcDJMx0JyYYOhrTM2nONWHKD8QHeT4a34bcoAZlJjchZS5fKulhwp6IpPmmbOcECnieJk3jBtjoDUHh3qQpZFGl2/Ubia6GG4fmJD30TWTDbRPEqFbDB4FfNGGRShtSXXfVYHGH9ptomHKW1eR7I67XXg17dSGJ/HKy0ZW8S0gmcqRuXW1i0ektgPKzxATG7bg15YM0Rc=
  - secure: p4CB1emwNjixgay6YjrgLXoFl6VFy/9eopQodZCOpz7jO9N7kkO3KqJRMaWKgkm0DCSLR0PUFzny2NUUBObpW0xHPhxaF1RA7EmWnAkm/AWsuJBsCXRweaNCLrLXtFnw/lAoubt/2qkXfRA05zJ+DaEqoxB6J8A6GpJGpuZFQ3W4mXxG5/M7b6KCo85zqZQUiu8eRw0isOp49eDdXvGRoDWu/bUUMx5aBem1CHxlvNalV97V7uYfOGYXONp0o+Xi1sDzXbzXFiZAM7kCgAk+1DSRP0spuxOAQsut3F6nlnetSln4vQGD86E5gIQ/9lnw2qyf5oiHOmR/pEy+2RKd4zpRMHKx39lskH82PmPAN6KM6kFcFvIYJ4gf2cFIm+s5xXerebIf2OiO3tavLZRUQf1N6nlDtgi9slXQPuxTjdEKCdlAcm9bS7nvzEI+dN7H9M0jtupR44PP3EtwAgTh0KkJSnRPMCPcJZfpdVpczWVrtao8jwb3mqzpYcl1MTU0XljV0ROZfC6Y+C5hHgbVu+AF4amg4R5GuUNwWu0Fn3Txk+1BruSFCq098NcXXLL1YP/vzCceJWpVj9Zs5Vh9GgEiuJUfipXJpP+Ig8N/vpMnl4HAWf8j7/Hs/4OgdXZJ+Ivl/yLzhotnjApQ6wDN3oi+60KnsozozNi9eEPhjK8=
