sudo: required
language: node_js
node_js:
        - 8
services:
        - docker
cache:
        directories:
                - node_modules
before_install:
        - npm i
script:
        - grunt
after_success:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "testnet" ]]; then
          docker build -t cangr/mvs-explorer-www:testnet .; docker push cangr/mvs-explorer-www:testnet; fi
env:
        secure: qtaZxvljW1r2ZjJRJR15rYsUBmQZ5/BPMDSF6Z9gDWpKuzqsbA0IWRx4KvU6sHhWw1TGNb2m5ghBXBY7U3gYaV4zZP8TTa0XVOl2QQUQBKEtp5vhDb9O3M7m3D0ONyzJjbuer8FWKBpDfNeSGeSv8mjcVzm+Zokw3SflcEACaucOXrwCxzUVWqHY6LbTQn8JZ69epZFaodLa7XEDTFY4v4TmwaVSpU8ByhLjIOjyluOVwSB01YVuIeo35Eumd+eX6ekrnat6PKoDVUHWEO9RUHfWWwDwprPJzwylYupkfdehJYpQyzHQfLoSSvHfZct938j+Y3yxg7NHyaHfmZwITWifNHOzK4bnOkFHI8ZxS8ydpAdnY3USU3r/BGjffnxT1jB8UGc2rUOZkzuc9dTxWwHbzBLch6NOqsX/5H7byMoHCbcE8UILoBno7cTx9dvvAJCBpoll0j2v5YY8MHrcuegEJEtboTSJxfuPzPl7ovLEZyWshDUa1rZch/nFnt+1twrQDXACtpVF1gLK6QsMjVZPTFARZ458RFRI9QLPMhU+kBKepEXxOQlkcFWeNiCvpXu48qgf90NFH69xw7I+8/REXloeRCjUIvZBR7hjWSaHqmJLCO4ENFFFHD2vjaOhV9kjBE5vJtNh6y/c2IB/k7/+ICd9CVcmAf3GiGuRSoY=
